[package]
name = "fastnbt"
description = "Serde deserializer for Minecraft's NBT format"
repository = "https://github.com/owengage/fastnbt"
readme = "README.md"
version = "2.4.4"
authors = ["Owen Gage <owengage@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["minecraft", "nbt", "serde"]
categories = ["parser-implementations"]

[dependencies]
arbitrary = { version = "1", optional = true, features = ["derive"] }
byteorder = "1"
cesu8 = "1.1"
indexmap = { version = "1.9", optional = true, features = ["serde"] }
serde = { version = "1", features=["derive"] }
serde_bytes = "0.11.5"

[features]
arbitrary1 = ["arbitrary"]
preserve-order = ["indexmap"]

[dev-dependencies]
flate2 = "1"
serde_json = "1"
